
@hostname =localhost:8081

### id url test
get  http://@{{hostname}}/GetEncounterById/1

### get encounter matches
get  http://@{{hostname}}/GetEncounterMatches/1

### delete all in collection
get  http://@{{hostname}}/ClearSolr

###/home/bijoy/code_experiments/solr-8.9.0/bin

### register encounter
POST http://@{{hostname}}/registerEncounter 
content-type: application/json

{
  
 "name": "testupdate",
  "age":11,
  "contactEmail": "asd233321@dd.co",
  "country": "AUS",
  "imageBiometricCaptureType" :"LIVE",
  "matches":[
    {"name":"first match", "pid":"PID002",
     "encounterTypes":[{"code":"VISA", "descritpion": "visa encounter"}]

          },
    
    {"name":"second match", "pid":"PID002",      
    "encounterTypes":[{"code":"GATES", "descritpion": "GATES CHECK IN"}]
    }
    ]
}

    "Joe Bloggs2",
      12,
      "03/11/2001",
      "Singapore",
      BiometricCaptureType.CHIP
### set up test data 
get http://@{{hostname}}/registerEncounter/
content-type: application/json

{
  
 "name": "testupdate",
  "age":"23",
  "contactEmail": "asd@dd.co",
  "country": "Singapore",
  "imageBiometricCaptureType" :"LIVE"
}

### H2 admin 
get http://localhost:8081/h2

###  swagger
get   http://localhost:8081/swagger-ui/

##solr
get http://localhost:8983

get http://localhost:8081/v2/api-docs
https://www.dariawan.com/tutorials/spring/springfox-bean-validators-swagger-documentation/
https://fullstackdeveloper.guru/2020/05/01/how-to-integrate-sqlite-database-with-spring-boot/


https://docs.jboss.org/hibernate/stable/validator/reference/en-US/html_single/#validator-customconstraints-simple

