
@hostname =localhost:8081

### id url test
get  http://@{{hostname}}/GetEncounterById/1

### id url test
get  http://@{{hostname}}/GetEncounterMatchCountById/1




### register encounter
POST http://@{{hostname}}/registerEncounter 
content-type: application/json

{
  
 "name": "testupdate4",
  "age":11,
  "contactEmail": "kdosugk@dd.com",
  "country": "INDI",
  "imageBiometricCaptureType" :"LIVE",
  "matches":[
    {"name":"first match1", "pid":"PID002",
     "encounterTypes":[{"code":"VISA", "descritpion": "visa encounter"}]

          },
    
    {"name":"second match3", "pid":"PID002",      
    "encounterTypes":[{"code":"GATES", "descritpion": "GATES CHECK IN"}]
    }
    ],
    "encounterLocations":[{"locationName":"Dubai"}, {"locationName":"Singapore"}]
}


###update 

POST http://@{{hostname}}/registerEncounter 
content-type: application/json

{
  "id": 1,
  "name": "testupdate6766",
  "age": 11,
  "contactEmail": "kdgk@dd.com",
  "country": "AUS",
  "imageBiometricCaptureType": "LIVE",
  "matches": [
    {
      "id": 4,
      "name": "first match",
      "pid": "PID002",
      "encounterTypes": [
        {
          "id": 5,
          "code": "VISA",
          "description": null
        }
      ]
    },
    {
      "id": 6,
      "name": "second match",
      "pid": "PID002",
      "encounterTypes": [
        {
          "id": 7,
          "code": "GATES",
          "description": null
        }
      ]
    }
  ],
  "encounterLocations": [
    {
      "id": 2,
      "locationName": "Dubai"
    },
    {
 
      "locationName": "Singapore"
    }
  ]
}






### get GetStoreById

get  http://@{{hostname}}/GetCodeTableRow/country/INDI



### delete all in collection
get  http://@{{hostname}}/ClearSolr

### H2 admin 
get http://localhost:8081/h2

###  swagger
get   http://localhost:8081/swagger-ui/

##solr
get http://localhost:8983

get http://localhost:8081/v2/api-docs
https://www.dariawan.com/tutorials/spring/springfox-bean-validators-swagger-documentation/
https://fullstackdeveloper.guru/2020/05/01/how-to-integrate-sqlite-database-with-spring-boot/


https://docs.jboss.org/hibernate/stable/validator/reference/en-US/html_single/#validator-customconstraints-simple

